spring:
  application:
    name: money-service

  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  output:
    ansi:
      enabled: always

logging.level:
  #org.springframework.transaction.interceptor: trace
  #org.hibernate.SQL: debug
  #org.hibernate.orm.jdbc.bind: trace
  #org.hibernate.orm.jdbc.extract: trace
  com.zaxxer.hikari.HikariConfig: debug
  com.zaxxer.hikari: trace

management:
  endpoints:
    web:
      exposure:
        include: prometheus

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/mypay_money
    username: myuser
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      #leak-detection-threshold: 2000

  redis:
    data:
      host: 127.0.0.1
      port: 6379

app:
  account-service-url: http://localhost:9000

server:
  port: 10000

---
spring:
  config:
    activate:
      on-profile: development

  jpa:
    hibernate:
      ddl-auto: none
