spring:
  application:
    name: account-service

  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.hibernate.orm.jdbc.extract: trace
  com.zaxxer.hikari.HikariConfig: debug
  com.zaxxer.hikari: trace

management:
  endpoints:
    web:
      exposure:
        include: prometheus

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/mypay_account
    username: myuser
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      leak-detection-threshold: 2000

server:
  port: 9000

---
spring:
  config:
    activate:
      on-profile: development

  jpa:
    hibernate:
      ddl-auto: none
